stages:
  - install
  - lint
  -test
  - build
  

cache:
  paths:
    - node_modules/

install-job:
  stage: install
  script:
    - npm install

lint-job:
  stage: lint
  script:
    - npm run lint
  artifacts:
    paths:
      - test/test.html
    untracked: true

test-job:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
    test/test.html
    untracked: true
      

  
build-job:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    untracked: true





    
    